# SPDX-License-Identifier: GPL-2.0
#
# Makefile for the linux kernel.
#

luo-y :=								\
		luo_core.o						\
		luo_files.o						\
		luo_ioctl.o						\
		luo_subsystems.o

obj-$(CONFIG_KEXEC_HANDOVER)		+= kexec_handover.o
obj-$(CONFIG_KEXEC_HANDOVER)		+= kho_array.o
obj-$(CONFIG_KEXEC_HANDOVER_DEBUG)	+= kexec_handover_debug.o

obj-$(CONFIG_LIVEUPDATE)		+= luo.o
obj-$(CONFIG_LIVEUPDATE_SELFTESTS)	+= luo_selftests.o
obj-$(CONFIG_LIVEUPDATE_SYSFS_API)	+= luo_sysfs.o
